pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/makelongvideo"

train_data:
  video_dir: "./data/webvid"
  n_sample_frames: 24
  width: 128 
  height: 128
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "a panda is surfing"
    - "a boy, wearing a birthday hat, is surfing"
    - "a raccoon is surfing, cartoon style"
    - "Iron Man is surfing in the desert"
  video_length: 24
  width: 128
  height: 128
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

#learning_rate: 3e-5
learning_rate: 1e-4
train_batch_size: 16
max_train_steps: 20000
checkpointing_steps: 10
validation_steps: 10
trainable_modules:
  - "temporal_conv"
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
  - "rel_pos_bias"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
gradient_accumulation_steps: 50
#resume_from_checkpoint: "outputs/man-surfing/checkpoint-1280"
